version: "3.0"

services:
    front-end:
        build:
            context: ./front-end
            dockerfile: ./deployments/Dockerfile-dev
        volumes:
            - ./front-end/:/app/
        ports:
            - 3000:3000
        stdin_open: true


    login:
        build:
            context: ./login
            dockerfile: ./deployments/Dockerfile-dev
        volumes:
            - ./login/:/app/
